services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - "6379-6379"

  django:
    container_name: django_timer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/Timer
    ports:
      - "8080-8080"
    links:
      - redis
